import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import { ThemeProvider } from "@/components/theme-provider";
import ThemeSwitcher from "@/components/ui/theme-switcher";
import NextTopLoader from "nextjs-toploader";

export const metadata: Metadata = {
  title: "Rankr",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased instrument-sans bg-[#fafafa]`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <nav className="pl-[68px] pr-5 pt-[30px] flex justify-between fixed min-w-full items-center">
            <Image src="/assets/logo.png" width={50} height={50} alt="" />
            <ThemeSwitcher />
          </nav>

          {children}
        </ThemeProvider>
        <NextTopLoader
          color="#2299DD" />
      </body>
    </html>
  );
}
